### ISSUE TITLE
task: Manuelle Dateneingabe

### ISSUE THREAD

**Issue by martinaottinger** [brichzin/SeminarInformatik#11]
## Wo erfolgen Änderungen? 
Die Klasse, die die Daten verwaltet, muss eine Schnittstelle zur manuellen Eingabe von Daten zur Verfügung stellen. 

## Was muss geändert werden? 
Methode anlegen

## Wie erfolgen die Änderungen? (Implementierungsdetails)
Es sollten alle nötigen Parameter wie Datum, Ort (Landkreis/Bundesland/Land), Anzahl, Art der Eintragung (Neuerkrankung, Todesfall, Genesung, evtl. auch negative Tests) mit übergeben werden können und dann adäquat gespeichert werden.

**Comment by brichzin** [comment]
Klassenname: Model
Ergänzung der Methode datenManuellEingeben()
Eingabedaten Prototyp 1: Anzahl Infizierte, Anzahl Todesfälle zugeordent einem konkreten Datum
