### ISSUE TITLE
task: graphische Oberfläche zur Dateneingabe

### ISSUE THREAD

**Issue by martinaottinger** [brichzin/SeminarInformatik#17]
## Wo erfolgen Änderungen? 
GUI

## Was muss geändert werden? 
Es muss für Moderatoren/Autoren eine graphische Oberfläche geschaffen werden, die alle für einen Datensatz zur Übermittlung an die Logik/Datenklasse nötigen Daten abfragt.

## Wie erfolgen die Änderungen? (Implementierungsdetails)
Es würde vermutlich ein einfaches Formular genügen, das die einzelnen Möglichkeiten als DropDown zur Verfügung stellt und diese Daten dann an die verarbeitende Logik weitergibt.

**Comment by Googolpl3x** [comment]
Klassenname: View (GUI)
Neue Methode datenEingeben( ) - Daten werden verarbeitet und an die Logik weitergegeben; Überprüfung ob Daten vollständig eingegeben wurden

Nutzung der Schnittstelle aus #11 

Button zum Absenden der Eingaben
Felder zur Eingabe der Daten

**Comment by ARuggaber** [comment]
Eingabe von Tag, Monat, Jahr, Anzahl neu Infizierte, Tote und Bundesland über GUI möglich.
Weitergabe von Jahr, Bundesland an das Model noch nicht im Model realisiert.
Datum wird auf Plausibilität geprüft auch Schaltjahre
