### ISSUE TITLE
User Story: einfache Datendarstellung

### ISSUE THREAD

**Issue by brichzin** [brichzin/SeminarInformatik#28]
## Beschreibung
Als Nutzer möchte ich daten zu Corona abrufen/sehen können um wichtige Informationen zu haben

**Comment by brichzin** [comment]
Task: tabellarische Ausgabe über die Konsole

**Comment by marionstadtmueller** [comment]
Ausgabe in Konsole
-> in Klasse View
-> Methode ausgabeTabellarisch
Klasse Model: neue Methode datenAuslesen

**Comment by martinaottinger** [comment]
Tabellarische Ausgabe mit Button im Hauptfenster eingefügt. 
Console öffnet sich und gibt eine Tabelle mit Kopfzeile aus. 
Als Ausgaben werden Tag, Monat, Jahr, Infizierte und Todesfälle berücksichtigt.
