### ISSUE TITLE
task: einfache Datenbasis suchen und 5 Datensätze zur Verfügung stellen

### ISSUE THREAD

**Issue by lsenka** [brichzin/SeminarInformatik#29]
## Wo erfolgen Änderungen? 
(z. B. in welcher Klasse)

## Was muss geändert werden? 
(z. B. Attribut, Methode)

**Comment by brichzin** [comment]
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm
--
